### ISSUE TITLE
пропуски в списке

### ISSUE THREAD

**Issue by f242** [fuflomycin/fuflomycin_app#28]
![image](https://github.com/user-attachments/assets/c5d04190-a00a-4a47-9470-7290656fdc17)
данные и кэш чистил
1.1.0
андроид 14

**Comment by bndby** [comment]
Спс, уже в процессе фиксаSent from Android device9 авг. 2024 г. 19:08 пользователь f242 ***@***.***> написал:
image.png (view on web)
данные и кэш чистил
1.1.0
андроид 14
